service: serverless-cicd

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  memorySize: 128
  timeout: 10


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: test
          method: get
